/**
 * Hand-rolled subset of the database types.
 *
 * In production this file is generated by `supabase gen types typescript`.
 * For now we declare just the columns the app currently reads/writes so
 * `Database` has a real shape and `useUser()` etc. stay typed.
 */

export type UserRole = 'admin' | 'nutritionist' | 'user'
export type UserTier = 'free' | 'basic' | 'premium' | 'vip'

export interface Profile {
  id: string
  role: UserRole
  tier: UserTier
  full_name: string | null
  avatar_url: string | null
  phone: string | null
  date_of_birth: string | null
  gender: string | null
  height_cm: number | null
  weight_kg: number | null
  target_weight_kg: number | null
  dietary_preferences: string[] | null
  allergies: string[] | null
  health_conditions: string[] | null
  activity_level: string | null
  primary_goal: string | null
  medical_notes: string | null
  preferred_locale: 'en' | 'ar'
  is_active: boolean
  last_seen_at: string | null
  created_at: string
  updated_at: string
  country?: string | null
  // Multi-coach (migration 020): is_head_coach distinguishes the owner-
  // coach (full nutritionist privileges + business areas like earnings
  // and store curation) from employee coaches (clients/content/plans
  // only). assigned_coach_id on customer profiles points at the coach
  // who owns that client.
  is_head_coach?: boolean
  assigned_coach_id?: string | null
}

export interface FeatureFlagRow {
  feature: string
  enabled_for_tiers: UserTier[]
  is_globally_enabled: boolean
  description: string | null
}

export interface PlatformSettingRow {
  key: string
  value: unknown
  value_ar: unknown | null
  description: string | null
}

export interface Subscription {
  id: string
  user_id: string
  tier: UserTier
  stripe_subscription_id: string | null
  stripe_customer_id: string | null
  status: string | null
  current_period_start: string | null
  current_period_end: string | null
  cancel_at_period_end: boolean
  created_at: string
  updated_at: string
}

export interface NutritionLog {
  id: string
  user_id: string
  logged_at: string
  meal_type: string | null
  food_name: string
  calories: number | null
  protein_g: number | null
  carbs_g: number | null
  fat_g: number | null
  fiber_g: number | null
  sugar_g: number | null
  sodium_mg: number | null
  serving_size: string | null
  source: string | null
  scanner_image_url: string | null
  notes: string | null
  created_at: string
}

export interface ProgressEntry {
  id: string
  user_id: string
  recorded_at: string
  weight_kg: number | null
  body_fat_percent: number | null
  muscle_mass_kg: number | null
  waist_cm: number | null
  water_intake_ml: number | null
  sleep_hours: number | null
  energy_level: number | null
  mood: number | null
  steps: number | null
  notes: string | null
  photo_urls: string[]
  created_at: string
}

export interface MealPlan {
  id: string
  client_id: string
  nutritionist_id: string
  title: string
  start_date: string
  end_date: string | null
  weeks: number
  is_active: boolean
  created_at: string
}

export interface MealPlanItem {
  id: string
  plan_id: string
  week_idx: number
  day_idx: number
  meal_type: string
  recipe_id: string | null
  custom_name: string | null
  notes: string | null
}

export interface Recipe {
  id: string
  created_by: string
  title: string
  title_ar: string | null
  description: string | null
  description_ar: string | null
  image_url: string | null
  prep_time_minutes: number
  cook_time_minutes: number
  servings: number
  difficulty: string | null
  calories_per_serving: number | null
  protein_g: number | null
  carbs_g: number | null
  fat_g: number | null
  ingredients: unknown
  instructions: unknown
  tags: string[]
  dietary_tags: string[]
  is_published: boolean
  views: number
  created_at: string
}

export interface Post {
  id: string
  author_id: string
  type: string
  title: string
  title_ar: string | null
  content: string | null
  content_ar: string | null
  image_url: string | null
  tags: string[]
  is_published: boolean
  scheduled_at: string | null
  published_at: string | null
  views: number
  reactions: { likes?: number; comments?: number } | null
  created_at: string
  updated_at: string
}

export interface Booking {
  id: string
  client_id: string
  nutritionist_id: string
  type: 'introCall' | 'followUp' | 'deepDive'
  scheduled_at: string
  duration_min: number
  status: 'scheduled' | 'completed' | 'cancelled' | 'noShow'
  notes: string | null
  meeting_url: string | null
  created_at: string
}

export interface Conversation {
  id: string
  client_id: string
  nutritionist_id: string
  last_message_at: string
  unread_count: number
  flagged: boolean
  created_at: string
}

export interface Message {
  id: string
  conversation_id: string
  sender_id: string
  body: string
  read: boolean
  created_at: string
}

export interface ClientNote {
  id: string
  client_id: string
  nutritionist_id: string
  body: string
  created_at: string
}

export interface Product {
  id: string
  name: string
  category: string
  /** Price in USD minor units (cents). Divide by 100 for display. */
  price_cents: number
  /** Crossed-out compare price in cents, when on sale. */
  compare_price_cents: number | null
  stock_quantity: number
  description: string | null
  nutritionist_note: string | null
  tags: string[]
  image_url: string | null
  is_nutritionist_pick: boolean
  is_active: boolean
  created_at: string
}

/**
 * Order line item shape — these live INSIDE `orders.items` as a JSONB
 * array, not in a separate table. unit_price is stored in cents.
 */
export interface OrderLineItem {
  product_id: string
  qty: number
  unit_price_cents: number
}

export interface Order {
  id: string
  user_id: string
  status: 'pending' | 'processing' | 'shipped' | 'delivered' | 'cancelled' | 'refunded'
  items: OrderLineItem[]
  subtotal_cents: number
  discount_cents: number
  total_cents: number
  shipping_address: { line1?: string; city?: string; country?: string } | null
  coupon_code: string | null
  stripe_payment_intent_id: string | null
  stripe_session_id: string | null
  tracking_number: string | null
  notes: string | null
  created_at: string
  updated_at: string
}

export interface Coupon {
  code: string
  discount_pct: number
  active: boolean
  expires_at: string | null
  created_at: string
}

export interface Notification {
  id: string
  user_id: string
  title: string
  body: string
  category: string
  href: string | null
  read: boolean
  created_at: string
}

export interface AiConversation {
  id: string
  user_id: string
  kind: 'scanner' | 'chat' | 'research'
  messages: unknown
  created_at: string
}

export interface ResearchDocument {
  id: string
  uploader_id: string
  name: string
  url: string
  size_mb: number
  created_at: string
}

export interface Milestone {
  id: string
  user_id: string
  type: string
  body: string
  supports: number
  comments: number
  created_at: string
}

export interface ApiKey {
  id: string
  name: string
  provider: string
  key_encrypted: string
  active: boolean
  last_used_at: string | null
  created_at: string
}

export interface AuditLog {
  id: string
  actor_id: string | null
  actor_role: UserRole | null
  action: string
  resource_type: string | null
  resource_id: string | null
  old_value: unknown | null
  new_value: unknown | null
  ip_address: string | null
  user_agent: string | null
  created_at: string
}

export interface ModerationFlag {
  id: string
  reporter_id: string | null
  target_table: string
  target_id: string
  reason: string
  severity: 'low' | 'medium' | 'high'
  resolution: 'pending' | 'kept' | 'removed'
  resolver_id: string | null
  resolved_at: string | null
  created_at: string
}

// Per-user Capacitor local-notification reminder preferences. Mirrors
// the 024_notification_preferences migration. Time columns serialise
// as "HH:MM:SS" strings.
export interface NotificationPreferencesRow {
  user_id: string
  breakfast_enabled: boolean
  breakfast_time: string
  lunch_enabled: boolean
  lunch_time: string
  dinner_enabled: boolean
  dinner_time: string
  hydration_enabled: boolean
  hydration_start_time: string
  hydration_end_time: string
  hydration_interval_hours: number
  workout_enabled: boolean
  workout_time: string
  updated_at: string
}

// Insert/upsert shape: user_id is required; every other column has
// a server-side default and can be omitted on first insert.
export type NotificationPreferencesInsert = { user_id: string } & Partial<
  Omit<NotificationPreferencesRow, 'user_id' | 'updated_at'>
>

// Tiny helper for Insert/Update generics
type Insertable<T extends { id?: unknown; created_at?: unknown }> =
  Partial<T> & Pick<T, never>

// Shape required by @supabase/ssr's typed client. Auto-generated types
// from `supabase gen types typescript` follow this exact structure.
export interface Database {
  public: {
    Tables: {
      profiles:           Tab<Profile, Partial<Profile> & { id: string }>
      feature_flags:      Tab<FeatureFlagRow, Partial<FeatureFlagRow> & { feature: string }>
      platform_settings:  Tab<PlatformSettingRow, { key: string; value: unknown; value_ar?: unknown; description?: string }>
      subscriptions:      Tab<Subscription,    Insertable<Subscription>>
      nutrition_logs:     Tab<NutritionLog,    Insertable<NutritionLog>>
      progress_entries:   Tab<ProgressEntry,   Insertable<ProgressEntry>>
      meal_plans:         Tab<MealPlan,        Insertable<MealPlan>>
      meal_plan_items:    Tab<MealPlanItem,    Insertable<MealPlanItem>>
      recipes:            Tab<Recipe,          Insertable<Recipe>>
      posts:              Tab<Post,            Insertable<Post>>
      bookings:           Tab<Booking,         Insertable<Booking>>
      conversations:      Tab<Conversation,    Insertable<Conversation>>
      messages:           Tab<Message,         Insertable<Message>>
      client_notes:       Tab<ClientNote,      Insertable<ClientNote>>
      products:           Tab<Product,         Insertable<Product>>
      orders:             Tab<Order,           Insertable<Order>>
      coupons:            Tab<Coupon,          Insertable<Coupon>>
      notifications:      Tab<Notification,    Insertable<Notification>>
      ai_conversations:   Tab<AiConversation,  Insertable<AiConversation>>
      research_documents: Tab<ResearchDocument, Insertable<ResearchDocument>>
      milestones:         Tab<Milestone,       Insertable<Milestone>>
      api_keys:           Tab<ApiKey,          Insertable<ApiKey>>
      audit_log:          Tab<AuditLog,        Insertable<AuditLog>>
      moderation_flags:   Tab<ModerationFlag,  Insertable<ModerationFlag>>
      notification_preferences: Tab<NotificationPreferencesRow, NotificationPreferencesInsert>
    }
    Views: { [key: string]: never }
    Functions: { [key: string]: never }
    Enums: {
      user_role: UserRole
      user_tier: UserTier
    }
    CompositeTypes: { [key: string]: never }
  }
}

interface Tab<Row, Insert> {
  Row: Row
  Insert: Insert
  Update: Partial<Row>
  Relationships: []
}
