import { useMemo } from 'react'
import { useAuth } from '@/contexts/AuthContext'

const TIER_FEATURES = {
  free: {
    hasAds: true,
    aiMessagesPerDay: 3,
    mealPlans: false,
    workoutPlans: false,
    photoRecognition: false,
    wearableIntegration: false,
    nutritionistAccess: false,
    advancedAnalytics: false,
    dataExport: false,
    barcodeScanner: false,
    foodDatabase: false,
    recipeDatabase: false,
    macroTracking: false,
    exerciseLibrary: false,
    goalTracking: false,
    healthStreaks: false,
    customNotifications: false,
    motivationalSupport: false,
    progressReports: false,
    workoutAnalytics: false,
    doctorConsultations: false,
    appointmentScheduling: false,
  },
  basic: {
    hasAds: true,
    aiMessagesPerDay: 5,
    mealPlans: true,
    workoutPlans: true,
    photoRecognition: false,
    wearableIntegration: false,
    nutritionistAccess: false,
    advancedAnalytics: false,
    dataExport: false,
    barcodeScanner: false,
    foodDatabase: false,
    recipeDatabase: false,
    macroTracking: false,
    exerciseLibrary: false,
    goalTracking: false,
    healthStreaks: false,
    customNotifications: false,
    motivationalSupport: false,
    progressReports: false,
    workoutAnalytics: false,
    doctorConsultations: false,
    appointmentScheduling: false,
  },
  premium: {
    hasAds: false,
    aiMessagesPerDay: 20,
    mealPlans: true,
    workoutPlans: true,
    photoRecognition: false,
    wearableIntegration: true,
    nutritionistAccess: false,
    advancedAnalytics: false,
    dataExport: false,
    barcodeScanner: true,
    foodDatabase: true,
    recipeDatabase: true,
    macroTracking: true,
    exerciseLibrary: true,
    goalTracking: true,
    healthStreaks: true,
    customNotifications: true,
    motivationalSupport: true,
    progressReports: false,
    workoutAnalytics: false,
    doctorConsultations: false,
    appointmentScheduling: false,
  },
  ultimate: {
    hasAds: false,
    aiMessagesPerDay: 50,
    mealPlans: true,
    workoutPlans: true,
    photoRecognition: false,
    wearableIntegration: true,
    nutritionistAccess: true,
    advancedAnalytics: true,
    dataExport: true,
    barcodeScanner: true,
    foodDatabase: true,
    recipeDatabase: true,
    macroTracking: true,
    exerciseLibrary: true,
    goalTracking: true,
    healthStreaks: true,
    customNotifications: true,
    motivationalSupport: true,
    progressReports: true,
    workoutAnalytics: true,
    doctorConsultations: false,
    appointmentScheduling: false,
  },
  elite: {
    hasAds: false,
    aiMessagesPerDay: -1, // unlimited
    mealPlans: true,
    workoutPlans: true,
    photoRecognition: true,
    wearableIntegration: true,
    nutritionistAccess: true,
    advancedAnalytics: true,
    dataExport: true,
    barcodeScanner: true,
    foodDatabase: true,
    recipeDatabase: true,
    macroTracking: true,
    exerciseLibrary: true,
    goalTracking: true,
    healthStreaks: true,
    customNotifications: true,
    motivationalSupport: true,
    progressReports: true,
    workoutAnalytics: true,
    doctorConsultations: true,
    appointmentScheduling: true,
  },
}

const PLAN_NAMES = {
  free: 'Free',
  basic: 'Basic',
  premium: 'Premium',
  ultimate: 'Ultimate',
  elite: 'Elite',
}

export const useFeatureAccess = () => {
  const { profile, subscription } = useAuth()

  return useMemo(() => {
    const tier = subscription?.tier || profile?.subscription_tier || 'free'
    const features = TIER_FEATURES[tier] || TIER_FEATURES.free

    return {
      planKey: tier,
      planName: PLAN_NAMES[tier] || 'Free',
      hasAds: features.hasAds,
      aiMessagesPerDay: features.aiMessagesPerDay,
      hasAccess: (feature) => features[feature] || false,
      features,
      isPremiumPlus: tier !== 'free' && tier !== 'basic',
      isUltimatePlus: tier === 'ultimate' || tier === 'elite',
      isElite: tier === 'elite',
    }
  }, [profile?.subscription_tier, subscription?.tier])
}

export default useFeatureAccess
